# Generated by Django 5.2.5 on 2025-10-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for sending registration invites', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='Whether this family member has registered'),
        ),
    ]
