# Generated by Django 5.2.5 on 2025-10-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_familymember_email_familymember_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='send_reports',
            field=models.BooleanField(default=False, help_text='Whether to send reports to this family member'),
        ),
    ]
