# Generated by Django 5.2.5 on 2025-10-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_familymember_send_reports'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together=set(),
        ),
    ]
