# Generated by Django 5.2.5 on 2025-10-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_familymember_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='can_view_all',
            field=models.BooleanField(default=False, help_text="Can view all family members' data"),
        ),
        migrations.AddField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Family Member')], default='member', help_text='User role in the family', max_length=10),
        ),
    ]
