# Generated by Django 5.2.5 on 2025-10-17 03:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_familymember_can_view_all_familymember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('user',)},
        ),
    ]
