# Generated by Django 5.2.5 on 2025-10-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_familymember_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together=set(),
        ),
    ]
