name: family_bookkeeping_flutter
description: "A comprehensive family bookkeeping system with Flutter frontend and Django backend."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # UI & Navigation
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Charts & Data Visualization
  fl_chart: ^0.66.0
  
  # Date & Time
  intl: ^0.19.0
  
  # File Operations
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  share_plus: ^7.2.2
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # CSV/Excel
  csv: ^6.0.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Background Tasks
  workmanager: ^0.5.2
  
  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  
  # Utilities
  uuid: ^4.2.1
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
